import Navigation from './components/Navigation.jsx'
import '../styles/global.css'

export const metadata = {
  title: 'Portafolios',
  description: 'Generated by Next.js',
}

export default function RootLayout({children}) {
  return ( 
    <html lang="en">
      <body>
        <Navigation/> 
        {children}
      </body>
    </html>
  )
}